Feat/typography component
keen/keen pull request #1002
Opened 2021-06-28 10:46 UTC by mczapkowicz

2021-06-28 14:45 UTC, maciejrybaniec requested changes

2021-06-28 14:45 UTC, maciejrybaniec commented on packages/ui-core/src/components/typography-settings/typography-settings.component.tsx
> +  onChange,
As we discussed - could You please add possibility to specify which properties are allowed to edit like for eg. text alignment etc.

2021-06-30 10:29 UTC, apryka commented on packages/ui-core/src/components/typography-settings/components/attribute-dropdown/attribute-dropdown.styles.ts
> +  font-family: 'Lato Regular', sans-serif;
please use `BodyText` from `keen.io/typography` here

2021-06-30 10:30 UTC, apryka commented on packages/ui-core/src/components/typography-settings/components/font-size/font-size.styles.ts
> +  font-size: 14px;
keen.io/typography

2021-06-30 10:31 UTC, apryka commented on packages/ui-core/src/components/typography-settings/components/option/option.component.ts
> +  font-family: 'Lato Regular', sans-serif;
keen.io/typography

2021-06-30 11:47 UTC, apryka approved these changes

2021-06-30 11:53 UTC, maciejrybaniec approved these changes

2021-06-30 11:56 UTC, merged