refactor: 💡 remove enzyme and update tests
keen/keen pull request #1288
Opened 2022-05-09 14:33 UTC by apryka

https://metakeen.atlassian.net/browse/FEE-902

2022-05-09 14:54 UTC, maciejrybaniec requested changes
LGTM. Just small typings adjustments and we could merge it.

2022-05-09 14:54 UTC, maciejrybaniec commented on packages/ui-core/src/components/color-adjuster/color-adjuster.component.test.tsx
> +  const props = {
Could You please provide here a better typings like for eg. `Partial<ComponentProps<typeof ColorAdjuster>>`

2022-05-09 14:54 UTC, maciejrybaniec commented on packages/ui-core/src/components/slider/interval-slider.component.test.tsx
> +  } as any;
Ditto - please, replace `any` in test with more specific props types as well.

2022-05-12 10:01 UTC, maciejrybaniec approved these changes

2022-05-12 10:33 UTC, mczapkowicz approved these changes

2022-05-12 13:15 UTC, stassiek02 approved these changes

2022-05-13 07:48 UTC, merged