Feat/fee 429 bar chart tooltip
keen/keen pull request #795
Opened 2021-03-04 08:59 UTC by apryka

https://metakeen.atlassian.net/browse/FEE-429

2021-03-04 12:30 UTC, maciejrybaniec requested changes

2021-03-04 12:30 UTC, maciejrybaniec commented on packages/charts/src/charts/bar/bar-tooltip-content.component.tsx
> +      ? formatScaleLabel(data[index][labelSelector], xScaleSettings)
`format` label based on on scale settings utility provided from **dataviz** layer

2021-03-04 12:30 UTC, maciejrybaniec commented on packages/charts/src/charts/bar/bar-chart.component.tsx
>                    formatValue={formatTooltip}
Use `TooltipFormatter` from `@keen.io/charts-utils` and format value with `formatValue()`.

2021-03-04 12:30 UTC, maciejrybaniec commented on packages/charts/src/components/tooltip-content/tooltip-content.component.tsx
> +  isList,
`isList is not required`

2021-03-04 12:30 UTC, maciejrybaniec commented on packages/charts/src/components/tooltip-content/tooltip-content.component.tsx
> +  scaleLabel,
Rename to not couple it with charts that uses `scale`

2021-03-05 08:05 UTC, maciejrybaniec approved these changes

2021-03-05 10:17 UTC, mczapkowicz commented on packages/charts/src/charts/bar/bar-tooltip-content.component.tsx
> +  console.log({ precision, formatLabel });
You missed console.log() ;)

2021-03-05 12:18 UTC, maciejrybaniec approved these changes

2021-03-05 13:23 UTC, merged