refactor: 💡 format tooltip for heatmap
keen/keen pull request #803
Opened 2021-03-05 12:20 UTC by apryka

https://metakeen.atlassian.net/browse/FEE-465

2021-03-05 15:26 UTC, maciejrybaniec approved these changes

2021-03-08 06:49 UTC, maciejrybaniec requested changes
Could You please add also additional unit tests to cover both `TooltipFormatter` cases.

2021-03-08 07:40 UTC, apryka commented
> Could You please add also additional unit tests to cover both `TooltipFormatter` cases.

👍 done

2021-03-08 10:40 UTC, maciejrybaniec approved these changes

2021-03-08 10:43 UTC, merged