Feat/fee 516 timezone enhancements
keen/keen pull request #851
Opened 2021-03-26 11:26 UTC by apryka

https://metakeen.atlassian.net/browse/FEE-516

2021-03-29 06:25 UTC, mczapkowicz approved these changes

2021-03-29 06:34 UTC, maciejrybaniec requested changes

2021-03-29 06:34 UTC, maciejrybaniec commented on packages/ui-core/src/components/timezone/timezone.component.tsx
> +const Row: FC<RowProps> = ({ data, index, style }) => {
Please, extract it to separate file under `components` directory.

2021-03-29 06:34 UTC, maciejrybaniec commented on packages/ui-core/src/components/timezone/timezone.component.tsx
> +                height={150}
Please, move it as component property `listHeight` with default value set to `150`

2021-03-29 06:34 UTC, maciejrybaniec commented on packages/ui-core/src/components/timezone/timezone.component.tsx
> +  timezone?: TimezoneType;
In my opinion we should not stick `1:1` with back-end schema. Current `timezone` value should be only `string` - that represents named timezone. Providing **utcOffset** just to set value should not be required a Explorer / Creator will be forced to persist it somewhere.

2021-03-29 06:34 UTC, maciejrybaniec commented on packages/ui-core/src/components/timezone/timezone.component.tsx
> +
```
const { name, offset } = useMemo(() => {
if (timezones.length === 0) {
  return {
   name: timezone
   offset: null,
  };
}
}, [timezone, timezones]) 
```

2021-03-29 10:51 UTC, maciejrybaniec commented on packages/ui-core/src/components/timezone/timezone.component.tsx
> +  timezones: TimezoneType[];
`TimezoneType` -> `TimezoneItem`

2021-03-31 08:38 UTC, maciejrybaniec approved these changes

2021-03-31 08:41 UTC, merged