fix: 🐛 remove default format value for funnel
keen/keen pull request #931
Opened 2021-05-04 11:02 UTC by apryka

https://metakeen.atlassian.net/browse/FEE-594

2021-05-04 12:10 UTC, mczapkowicz submitted a review, later dismissed

2021-05-04 12:56 UTC, maciejrybaniec requested changes

2021-05-04 12:56 UTC, maciejrybaniec commented on packages/charts/src/charts/funnel/funnel-chart.component.test.tsx
> +test('renders values without default formatting', () => {
As default formatting is not applied I believe the better description will be: `renders values without formatting`

2021-05-05 12:13 UTC, dariuszlacheta approved these changes

2021-05-06 12:07 UTC, maciejrybaniec approved these changes

2021-05-06 12:12 UTC, merged