feat: 🎸 bar chart legend interactions
keen/keen pull request #957
Opened 2021-05-17 10:25 UTC by apryka

https://metakeen.atlassian.net/browse/FEE-543

2021-05-17 10:56 UTC, mczapkowicz approved these changes

2021-05-17 12:46 UTC, maciejrybaniec requested changes

2021-05-17 12:46 UTC, maciejrybaniec commented on packages/charts/src/charts/bar/components/bars/bars.component.tsx
> +  activeKey?: string;
What do You think about change type definition to `string | null`. Then in `useEffect` also change this strange `typeof` condition:
```
 if (isActive === null) {
     return;
 }
```

2021-05-17 12:47 UTC, maciejrybaniec commented on packages/charts/src/charts/bar/components/bars/bars.component.tsx
> +  activeKey?: string;
We could also set `activeKey` default as a `null`

2021-05-19 14:02 UTC, mczapkowicz submitted a review, later dismissed

2021-05-20 11:40 UTC, maciejrybaniec approved these changes

2021-05-20 11:47 UTC, merged