feat: 🎸 slider for theming
keen/keen pull request #971
Opened 2021-05-25 13:11 UTC by apryka

https://metakeen.atlassian.net/browse/FEE-666

2021-05-26 05:58 UTC, maciejrybaniec requested changes

2021-05-26 05:58 UTC, maciejrybaniec commented on packages/ui-core/src/components/slider/interval-slider.stories.tsx
> +export const withRulerTheming = () => {
Based on what we discussed the user should be able to use values between defined ruler ranges.
In use case on the image - it should be **12**
<img width="353" alt="Zrzut ekranu 2021-05-26 o 07 57 10" src="https://user-images.githubusercontent.com/7753369/119609567-195d0e00-bdf8-11eb-96a3-fda10bd47bf9.png">

2021-05-27 08:57 UTC, mczapkowicz approved these changes

2021-05-27 16:39 UTC, mczapkowicz approved these changes

2021-05-28 06:30 UTC, maciejrybaniec approved these changes

2021-05-28 06:33 UTC, merged